trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  PYTHON_VERSION: '3.9'

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)
    addToPath: true
  displayName: "Set Python Version"

# - task: Npm@1
#   inputs:
#     command: 'install'

- script: |
    npm i --location=global appium
    appium
  displayName: "Install Appium"

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Dependencies"


- script: |
    echo "##vso[task.setvariable variable=PYTHONPATH]$(System.DefaultWorkingDirectory)"
  displayName: "Set PYTHONPATH"

- script: |
    ls -la
    pytest TestCases --junitxml=TestResults/test-results.xml
  displayName: "Run Tests with Pytest"

- task: PublishTestResults@2
  inputs:
    testResultsFiles: 'TestResults/test-results.xml'
    testRunTitle: 'AppiumPython Test Results'
  displayName: "Publish Test Results"
