trigger:
- main

pool:
  vmImage: 'ubuntu-20.04'

variables:
  PYTHON_VERSION: '3.9'
  ANDROID_HOME: $(System.DefaultWorkingDirectory)/android-sdk-linux
  PATH: $(ANDROID_HOME)/tools:$(ANDROID_HOME)/platform-tools
  APPIUM_PORT: 4723
  DEVICE_NAME: "Android Emulator"
  PLATFORM_NAME: "Android"
  PLATFORM_VERSION: "11"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)
    addToPath: true
  displayName: "Set Python Version"

- script: |
      sudo apt update
      sudo apt install -y openjdk-11-jdk
      curl -sL https://dl.google.com/android/repository/commandlinetools-linux-7583922_latest.zip -o android-tools.zip
      unzip android-tools.zip -d $(ANDROID_HOME)
      yes | $(ANDROID_HOME)/cmdline-tools/bin/sdkmanager --licenses
      $(ANDROID_HOME)/cmdline-tools/bin/sdkmanager "platform-tools" "platforms;android-30" "build-tools;30.0.3"
  displayName: 'Install Android SDK'

- script: |
    python -m pip install --upgrade pip
    pip install virtualenv
    virtualenv venv
    source venv/bin/activate
    pip install -r requirements.txt
  displayName: "Install Dependencies in Virtualenv"

- script: |
    npm install -g appium
    appium driver install uiautomator2
  displayName: 'Install Appium and Android driver'

- script: |
    # Start Appium server and ensure it is fully running
    nohup appium -ka 4723 --log-level debug > appium.log 2>&1 &
    sleep 10  # Give Appium some time to fully start
  displayName: 'Start Appium Server'

- script: |
    # Run tests using pytest
    pytest TestCases --junitxml=TestResults/test-results.xml
  displayName: 'Run Appium Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Appium Tests'
