trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  PYTHON_VERSION: '3.9'  # Ensure this matches your project's Python version

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)  # This variable must exist
    addToPath: true

- script: |
    python -m unittest discover -s TestCases -p "test_*.py" -v
  displayName: "Run Tests"

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/TEST-*.xml'
    testRunTitle: 'AppiumPython Test Results'
  displayName: "Publish Test Results"
