trigger:
- main

pool:
  vmImage: 'windows-latest'  # Use a Windows-based VM

variables:
  ANDROID_HOME: $(System.DefaultWorkingDirectory)/android-sdk-windows
  PATH: $(ANDROID_HOME)/tools:$(ANDROID_HOME)/platform-tools:$(PATH)
  APPIUM_PORT: 4723
  DEVICE_NAME: "Android Emulator"
  PLATFORM_NAME: "Android"
  PLATFORM_VERSION: "11"

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true
  displayName: "Set Python Version"

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Dependencies"

- script: |
    echo "##vso[task.setvariable variable=PYTHONPATH]$(System.DefaultWorkingDirectory)"
  displayName: "Set PYTHONPATH"

- script: |
    # Install Chocolatey if not installed
    Set-ExecutionPolicy Bypass -Scope Process -Force; 
    iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
  displayName: 'Install Chocolatey'

- script: |
    # Install OpenJDK 11 and download Android SDK tools
    choco install openjdk11
    Invoke-WebRequest -Uri "https://dl.google.com/android/repository/commandlinetools-win-7583922_latest.zip" -OutFile "android-tools.zip"
    Expand-Archive -Path android-tools.zip -DestinationPath $(ANDROID_HOME)
    & "$(ANDROID_HOME)\cmdline-tools\bin\sdkmanager" --licenses
    & "$(ANDROID_HOME)\cmdline-tools\bin\sdkmanager" "platform-tools" "platforms;android-30" "build-tools;30.0.3"
  displayName: 'Install Android SDK and JDK'

- script: |
    npm install -g appium
    appium driver install uiautomator2
  displayName: 'Install Appium and Android driver'

- script: |
    # Start Appium server
    Start-Process -NoNewWindow -FilePath "appium" -ArgumentList "--port", "4723", "--log-level", "debug"
  displayName: 'Start Appium Server'

- script: |
    # Run tests using pytest
    python -m unittest discover -s TestCases -p "test_*.py" -v
  displayName: 'Run Appium Tests'

- task: PublishTestResults@2
  inputs:
    testResultsFiles: '**/test-*.xml'
    testRunTitle: 'Appium Tests'