trigger:
- main

pool:
  vmImage: 'windows-latest'

variables:
  PYTHON_VERSION: '3.9'  # Ensure this matches your project's Python version

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: $(PYTHON_VERSION)  # This variable must exist
    addToPath: true

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: "Install Dependencies"

- script: |
    python -m unittest discover -s tests -p "*.py"
  displayName: "Run Tests"
